# Generated by Django 4.0.6 on 2022-09-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Misceláneo')),
                ('link', models.URLField(max_length=250)),
                ('public', models.BooleanField(default=True, verbose_name='¿Público?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
            ],
            options={
                'verbose_name': 'Link Misceláneo',
                'verbose_name_plural': 'Links Misceláneos',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Red')),
                ('link', models.URLField(max_length=250)),
                ('public', models.BooleanField(default=True, verbose_name='¿Público?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes sociales',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificada el'),
        ),
    ]
